/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Fujitsu
 */
public class BoardGame extends MyFrame {

    /**
     * Creates new form BoardGame
     */
    public BoardGame() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void printLog(String[] args)
    {
        String ret = "";
        for(int i = 0; i < args.length; i++)
        {
            ret += args[i];
        }
        ChatBoxText.append(ret);
    }
    
    public void drawCoordinate(int x, int y, int playerId)
    {
        int index = ((x * 20) + y);
        buttons[index].setText(playerId + "");
    }
    
    public void joinRoom(int roomId)
    {
        RoomIDLabel.setText(roomId + "");
    }
    
    public static MyButton buttons[] = new MyButton[400];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoardPanel = new javax.swing.JPanel();
        InfoGamePanel = new javax.swing.JPanel();
        ListOfPlayerPane = new javax.swing.JScrollPane();
        ListOfPlayerText = new javax.swing.JTextArea();
        RoomIDLabel = new javax.swing.JLabel();
        ChatBoxPane = new javax.swing.JScrollPane();
        ChatBoxText = new javax.swing.JTextArea();
        ChatInputField = new javax.swing.JTextField();
        ChatBoxLabel = new javax.swing.JLabel();
        ChatSendButton = new javax.swing.JButton();
        WhosTurnPane = new javax.swing.JScrollPane();
        WhosTurnText = new javax.swing.JTextArea();
        WhosTurnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BoardPanel.setPreferredSize(new java.awt.Dimension(900, 700));
        BoardPanel.setLayout(new java.awt.GridLayout(20, 20));

        ListOfPlayerText.setEditable(false);
        ListOfPlayerText.setColumns(20);
        ListOfPlayerText.setRows(5);
        ListOfPlayerText.setText("List of Player");
        ListOfPlayerPane.setViewportView(ListOfPlayerText);

        RoomIDLabel.setText("Room ID");

        ChatBoxText.setEditable(false);
        ChatBoxText.setColumns(20);
        ChatBoxText.setRows(5);
        ChatBoxPane.setViewportView(ChatBoxText);

        ChatInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatInputFieldActionPerformed(evt);
            }
        });

        ChatBoxLabel.setText("Chat Box");

        ChatSendButton.setText("Send");
        ChatSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatSendButtonActionPerformed(evt);
            }
        });

        WhosTurnText.setEditable(false);
        WhosTurnText.setColumns(20);
        WhosTurnText.setRows(1);
        WhosTurnPane.setViewportView(WhosTurnText);

        WhosTurnLabel.setText("Turn");

        javax.swing.GroupLayout InfoGamePanelLayout = new javax.swing.GroupLayout(InfoGamePanel);
        InfoGamePanel.setLayout(InfoGamePanelLayout);
        InfoGamePanelLayout.setHorizontalGroup(
            InfoGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RoomIDLabel)
                    .addGroup(InfoGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(InfoGamePanelLayout.createSequentialGroup()
                            .addComponent(ChatInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ChatSendButton))
                        .addComponent(ChatBoxPane)
                        .addComponent(ListOfPlayerPane)
                        .addComponent(ChatBoxLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoGamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WhosTurnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WhosTurnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        InfoGamePanelLayout.setVerticalGroup(
            InfoGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoGamePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(RoomIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListOfPlayerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfoGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(WhosTurnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WhosTurnLabel))
                .addGap(34, 34, 34)
                .addComponent(ChatBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChatBoxPane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChatInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChatSendButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(InfoGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        for (int i = 0; i < 400; i++)
        {
            buttons[i] = new MyButton();
            buttons[i].absis = (i / 20);
            buttons[i].ordinat = (i % 20);
            BoardPanel.add(buttons[i]);
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChatSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatSendButtonActionPerformed
        // TODO add your handling code here:
        adaCommand = true;
        type = "message";
        paramString = ChatInputField.getText();
        ChatInputField.setText(" ");
    }//GEN-LAST:event_ChatSendButtonActionPerformed

    private void ChatInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChatInputFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGame().setVisible(true);
            }
        });
    }

    public class MyButton extends JButton implements ActionListener
    {
        int playagain = 1000;
        boolean win = false;
        boolean end = false;
        String letter;
        public int absis;
        public int ordinat;
        public MyButton()
        {
            super();
            letter = " ";
            setFont(new Font("Dialog", 1, 10));
            setText(letter);
            addActionListener(this);
        }

        public void actionPerformed(ActionEvent e)
        {
            adaCommand = true;
            type = "coordinate";
            paramInt[0] = absis;
            paramInt[1] = ordinat;
            
            //System.out.println("absis = " + absis + " ordinat = " + ordinat);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JLabel ChatBoxLabel;
    private javax.swing.JScrollPane ChatBoxPane;
    private javax.swing.JTextArea ChatBoxText;
    private javax.swing.JTextField ChatInputField;
    private javax.swing.JButton ChatSendButton;
    private javax.swing.JPanel InfoGamePanel;
    private javax.swing.JScrollPane ListOfPlayerPane;
    private javax.swing.JTextArea ListOfPlayerText;
    private javax.swing.JLabel RoomIDLabel;
    private javax.swing.JLabel WhosTurnLabel;
    private javax.swing.JScrollPane WhosTurnPane;
    private javax.swing.JTextArea WhosTurnText;
    // End of variables declaration//GEN-END:variables
}
